import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

import React, { useState } from "react";
import "react-quill/dist/quill.snow.css";
import dynamic from "next/dynamic";

const ReactQuill = dynamic(import("react-quill"), {
  ssr: false,
});
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [value, setValue] = useState("");

  const sampleConfig = {
    toolbar: [
      { list: "bullet" },
      { size: ["small", false, "large", "huge"] },
      "bold",
      "italic",
      { background: [] },
    ],
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <ReactQuill
            modules={sampleConfig}
            theme="snow"
            value={value}
            onChange={setValue}
          />
        </div>
      </main>
    </>
  );
}
